"""CLI helper that emits TypeScript definitions for the schema package."""

from __future__ import annotations

import argparse
import inspect
import types as pytypes
import typing
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, ForwardRef, Iterable, Sequence, Type, get_args, get_origin

from pydantic import BaseModel

from .. import classroom_summary as classroom_summary_module
from .. import training_summary as training_summary_module
from ..department import analysis as department_analysis_module
from ..department import report as department_report_module
from ..user_summary import analysis as user_summary_analysis_module
from ..user_summary import report as user_summary_report_module

_DEFAULT_OUTPUT = Path("typescript/etrain-schema.d.ts")

_MODULES = [
    classroom_summary_module,
    training_summary_module,
    department_analysis_module,
    department_report_module,
    user_summary_analysis_module,
    user_summary_report_module,
]

_TYPE_ALIASES = {
    "ChoiceDetail": classroom_summary_module.ChoiceDetail,
}

_UNION_TYPES = tuple(t for t in (pytypes.UnionType, getattr(typing, "Union", None)) if t)
_LITERAL_TYPE = getattr(typing, "Literal", None)
_ANNOTATED_TYPE = getattr(typing, "Annotated", None)


def _collect_models() -> Sequence[Type[BaseModel]]:
    models: list[Type[BaseModel]] = []
    seen: set[type[Any]] = set()
    for module in _MODULES:
        for _, obj in inspect.getmembers(module, inspect.isclass):
            if not issubclass(obj, BaseModel):
                continue
            if obj.__module__ != module.__name__:
                continue
            if obj in seen:
                continue
            seen.add(obj)
            models.append(obj)
    models.sort(key=lambda cls: (cls.__module__, cls.__name__))
    return models


def _literal_token(value: Any) -> str:
    if isinstance(value, str):
        return f'"{value}"'
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    return str(value)


def _annotation_to_ts(annotation: Any) -> str:
    if annotation is None:
        return "any"

    if isinstance(annotation, ForwardRef):
        return annotation.__forward_arg__

    origin = get_origin(annotation)
    args = get_args(annotation)

    if origin in _UNION_TYPES:
        union_args = args or (annotation,)
        parts = [
            _annotation_to_ts(arg)
            for arg in union_args
        ]
        # Preserve order but remove duplicates.
        deduped: list[str] = []
        for part in parts:
            if part not in deduped:
                deduped.append(part)
        return " | ".join(deduped)

    if origin is tuple and len(args) == 2 and args[1] is Ellipsis:
        return f"{_annotation_to_ts(args[0])}[]"

    if origin in {list, tuple, set}:
        inner = args[0] if args else Any
        return f"{_annotation_to_ts(inner)}[]"

    if origin is ForwardRef:
        return str(args[0])

    if origin is _LITERAL_TYPE:
        return " | ".join(_literal_token(value) for value in args)

    if origin is _ANNOTATED_TYPE:
        return _annotation_to_ts(args[0])

    if inspect.isclass(annotation):
        if issubclass(annotation, BaseModel):
            return annotation.__name__
        if annotation is str:
            return "string"
        if annotation in {int, float}:  # type: ignore[comparison-overlap]
            return "number"
        if annotation is bool:
            return "boolean"

    if annotation is Any:
        return "any"
    if annotation is type(None):  # noqa: E721
        return "null"

    return "unknown"


def _field_optional(field: Any) -> bool:
    marker = getattr(field, "is_required", None)
    if callable(marker):
        return not marker()
    if isinstance(marker, bool):
        return not marker
    return False


def _render_model(model: Type[BaseModel]) -> str:
    lines = [f"export interface {model.__name__} {{"]
    for name, field in model.model_fields.items():
        ts_type = _annotation_to_ts(field.annotation)
        optional = _field_optional(field)
        suffix = "?" if optional else ""
        lines.append(f"    {name}{suffix}: {ts_type};")
    lines.append("}")
    return "\n".join(lines)


def _render_aliases() -> str:
    chunks = []
    for name, alias_type in _TYPE_ALIASES.items():
        chunks.append(f"export type {name} = {_annotation_to_ts(alias_type)};")
    return "\n".join(chunks)


def _render_typescript(models: Iterable[Type[BaseModel]]) -> str:
    timestamp = datetime.now(timezone.utc).isoformat()
    header = (
        "// ------------------------------------------------------------------\n"
        "// Auto-generated by etrain-schema-ts.\n"
        f"// Generated at: {timestamp}\n"
        "// Do not edit manually. Run `etrain-schema-ts` to regenerate.\n"
        "// ------------------------------------------------------------------\n\n"
    )
    aliases = _render_aliases()
    body = "\n\n".join(_render_model(model) for model in models)
    return header + aliases + "\n\n" + body + "\n"


def _write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main(output: Path | None = None) -> Path:
    output_path = output or _DEFAULT_OUTPUT
    models = _collect_models()
    typescript = _render_typescript(models)
    _write_if_changed(output_path, typescript)
    return output_path


def cli(argv: Sequence[str] | None = None) -> None:  # pragma: no cover - CLI glue
    parser = argparse.ArgumentParser(description="Generate TypeScript definitions")
    parser.add_argument(
        "--out",
        type=Path,
        default=_DEFAULT_OUTPUT,
        help=f"Destination file (default: {_DEFAULT_OUTPUT})",
    )
    args = parser.parse_args(argv)
    target = main(args.out)
    print(f"Wrote TypeScript definitions to {target}")


if __name__ == "__main__":  # pragma: no cover
    cli()
